name: upnp
version: 2.0.1
description: Universal Plugin and Play Host/Client
homepage: https://github.com/SpinlockLabs/upnp.dart
dependencies:
  xml: "^6.2.2"
  crypto: "^3.0.0"
environment:
  sdk: ">=2.0.0 <3.0.0"

